import cmath
a = float(input(print("Enter the values of a")))
b = float(input(print("Enter the values of b ")))
c = float(input(print("Enter the values of c")))
d = (b**2) - (4*a*c)
sol1 = (-b-cmath.sqrt(d)) / (2*a)
sol2 = (-b+cmath.sqrt(d)) / (2*a)
print(d)
print(sol1)
print(sol2)